---
title: Henry's Data Science Blog
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: henry.neeb@gmail.com
description: This site is my adventure into data science after school.
baseurl: 
url: https://hneeb.github.io
github_username: hneeb
markdown: kramdown
theme: minima
gems:
- jekyll-feed
